import json
import os
from event_collector import EventCollector

# Define events to add
events_to_add = [
    {
        "Nome do Evento": "11º Congresso de Inovação da Indústria",
        "Tipo": "Congresso",
        "Data / Período": "25-26 de março, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Transição Ecológica e Digital / Inovação Industrial",
        "Soluções DSW com aderência": "NX, Teamcenter, Opcenter, Siemens Xcelerator",
        "Público-alvo": "Misto (Indústria, Academia, Governo, Startups)",
        "Organização responsável": "CNI / SEBRAE",
        "Site / URL": "https://congressodeinovacao.com.br/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Maior evento de inovação industrial da AL; foca em deep techs e digitalização produtiva.",
        "Oportunidade de atuação": "Patrocinador / Palestrante"
    },
    {
        "Nome do Evento": "Hospitalar 2026",
        "Tipo": "Feira",
        "Data / Período": "19-22 de maio, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Ciências da Vida & MedTech",
        "Soluções DSW com aderência": "NX (Medical Devices), Teamcenter, Polarion (Compliance)",
        "Público-alvo": "Indústria / Hospitais / Investidores",
        "Organização responsável": "Informa Markets",
        "Site / URL": "https://www.hospitalar.com/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Principal evento de saúde da AL; alta aderência para design de dispositivos médicos e gestão de ciclo de vida.",
        "Oportunidade de atuação": "Expositor / Parceiro"
    },
    {
        "Nome do Evento": "Hannover Messe 2026",
        "Tipo": "Feira / Summit",
        "Data / Período": "20-24 de abril, 2026",
        "Local": "Hannover, Alemanha",
        "Vertical / Tema principal": "Industrial Machinery / Automação / Digitalização",
        "Soluções DSW com aderência": "Todo o portfólio Siemens Xcelerator",
        "Público-alvo": "Indústria / Startups / Acadêmicos",
        "Organização responsável": "Deutsche Messe AG",
        "Site / URL": "https://www.hannovermesse.de/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Evento global de referência para Indústria 4.0 onde a Siemens é protagonista histórica.",
        "Oportunidade de atuação": "Expositor / Patrocinador"
    },
    {
        "Nome do Evento": "FEIMEC 2026",
        "Tipo": "Feira",
        "Data / Período": "5-9 de maio, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Industrial Machinery / Máquinas-Ferramenta",
        "Soluções DSW com aderência": "NX CAM, Solid Edge, Teamcenter, Opcenter",
        "Público-alvo": "Indústria / Engenheiros",
        "Organização responsável": "ABIMAQ / Informa Markets",
        "Site / URL": "https://www.feimec.com.br/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Principal feira de máquinas e equipamentos da AL; foco direto em manufatura e automação.",
        "Oportunidade de atuação": "Expositor / Patrocinador"
    },
    {
        "Nome do Evento": "LAAD Defence & Security 2026",
        "Tipo": "Feira",
        "Data / Período": "14-16 de abril, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Aeroespacial & Defesa",
        "Soluções DSW com aderência": "NX, Simcenter, Polarion, Teamcenter",
        "Público-alvo": "Indústria / Forças Armadas / Governo",
        "Organização responsável": "Creative Events Brazil",
        "Site / URL": "https://www.laadexpo.com.br/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Maior feira de defesa e segurança da AL; vertical estratégica com alta complexidade de engenharia.",
        "Oportunidade de atuação": "Expositor / Participante"
    },
    {
        "Nome do Evento": "ROG.e (Rio Oil & Gas) 2026",
        "Tipo": "Conferência / Feira",
        "Data / Período": "21-24 de setembro, 2026",
        "Local": "Rio de Janeiro, Brasil",
        "Vertical / Tema principal": "Energia & Utilities / Óleo & Gás",
        "Soluções DSW com aderência": "Simcenter, Teamcenter, Insights Hub (IoT)",
        "Público-alvo": "Indústria / Engenheiros / Investidores",
        "Organização responsável": "IBP (Instituto Brasileiro de Petróleo e Gás)",
        "Site / URL": "https://roge.energy/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Principal evento de energia da AL; foco em ativos críticos e gêmeo digital para offshore.",
        "Oportunidade de atuação": "Expositor / Palestrante"
    },
    {
        "Nome do Evento": "Agrishow 2026",
        "Tipo": "Feira",
        "Data / Período": "27 de abril - 1 de maio, 2026",
        "Local": "Ribeirão Preto, Brasil",
        "Vertical / Tema principal": "Industrial Machinery (Agro) / Tecnologia Rural",
        "Soluções DSW com aderência": "Solid Edge, NX, Opcenter, Teamcenter",
        "Público-alvo": "Indústria / Produtores / Startups (Agtech)",
        "Organização responsável": "Informa Markets / ABIMAQ",
        "Site / URL": "https://www.agrishow.com.br/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Uma das maiores feiras agrícolas do world; essencial para design de maquinário pesado e digitalização do campo.",
        "Oportunidade de atuação": "Expositor / Parceiro"
    },
    {
        "Nome do Evento": "Fispal Tecnologia 2026",
        "Tipo": "Feira",
        "Data / Período": "16-19 de junho, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Bens de Consumo / Embalagem / Alimentos",
        "Soluções DSW com aderência": "Opcenter (MES), Tecnomatix, Insights Hub",
        "Público-alvo": "Indústria / Engenheiros de Produção",
        "Organização responsável": "Informa Markets",
        "Site / URL": "https://www.fispaltecnologia.com.br/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Foco total em eficiência de linha de produção e embalagem; aderência imediata a MES e simulação de fábrica.",
        "Oportunidade de atuação": "Expositor / Patrocinador"
    },
    {
        "Nome do Evento": "Realize LIVE Americas 2026",
        "Tipo": "Conferência / Summit",
        "Data / Período": "1-4 de junho, 2026",
        "Local": "Detroit, EUA",
        "Vertical / Tema principal": "Cross-industry / Digital Transformation",
        "Soluções DSW com aderência": "Todo o portfólio Siemens DSW",
        "Público-alvo": "Indústria / Usuários / Líderes de TI",
        "Organização responsável": "Siemens Digital Industries Software",
        "Site / URL": "https://www.siemens.com/realizelive",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Evento oficial da Siemens para usuários e parceiros; Detroit foca em Automotive & Aerospace.",
        "Oportunidade de atuação": "Organizador / Palestrante"
    },
    {
        "Nome do Evento": "Realize LIVE Europe 2026",
        "Tipo": "Conferência / Summit",
        "Data / Período": "29 de junho - 1 de julho, 2026",
        "Local": "Amsterdam, Holanda",
        "Vertical / Tema principal": "Cross-industry / Digital Transformation",
        "Soluções DSW com aderência": "Todo o portfólio Siemens DSW",
        "Público-alvo": "Indústria / Usuários / Acadêmicos",
        "Organização responsável": "Siemens Digital Industries Software",
        "Site / URL": "https://www.siemens.com/realizelive",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Edição europeia do principal evento da Siemens; foco em sustentabilidade e digital thread.",
        "Oportunidade de atuação": "Organizador / Palestrante"
    },
    {
        "Nome do Evento": "Embedded World 2026",
        "Tipo": "Feira / Conferência",
        "Data / Período": "10-12 de março, 2026",
        "Local": "Nuremberg, Alemanha",
        "Vertical / Tema principal": "Eletrônicos & Semicondutores / Embedded Systems",
        "Soluções DSW com aderência": "Polarion (ALM), Capital (EDA)",
        "Público-alvo": "Engenheiros / Indústria / Academia",
        "Organização responsável": "NürnbergMesse",
        "Site / URL": "https://www.embedded-world.de/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Referência mundial para software embarcado e eletrônica; crucial para Polarion e portfólio EDA.",
        "Oportunidade de atuação": "Expositor / Palestrante"
    },
    {
        "Nome do Evento": "South Summit Brazil 2026",
        "Tipo": "Summit / Demo Day",
        "Data / Período": "25-27 de março, 2026",
        "Local": "Porto Alegre, Brasil",
        "Vertical / Tema principal": "Ecossistema de Inovação / Startups",
        "Soluções DSW com aderência": "Mendix, Siemens Xcelerator para Startups",
        "Público-alvo": "Startups / Investidores / Indústria",
        "Organização responsável": "South Summit / Governo do RS",
        "Site / URL": "https://www.southsummit.io/brazil/",
        "Nível de relevância": "Média",
        "Justificativa Relevância": "Grande visibilidade para conexão com startups e novos negócios (Mendix / low-code).",
        "Oportunidade de atuação": "Patrocinador / Palestrante"
    },
    {
        "Nome do Evento": "Web Summit Rio 2026",
        "Tipo": "Summit",
        "Data / Período": "8-11 de junho, 2026",
        "Local": "Rio de Janeiro, Brasil",
        "Vertical / Tema principal": "Tecnologia / Inovação Digital",
        "Soluções DSW com aderência": "Mendix, Insights Hub, Industrial AI",
        "Público-alvo": "Startups / Investidores / Misto",
        "Organização responsável": "Web Summit",
        "Site / URL": "https://rio.websummit.com/",
        "Nível de relevância": "Média",
        "Justificativa Relevância": "Principal evento de tech 'genérico' da AL; bom para prospecção de startups de software industriais.",
        "Oportunidade de atuação": "Patrocinador / Palestrante"
    },
    {
        "Nome do Evento": "Future Digital Twin & AI USA 2026",
        "Tipo": "Summit / Conferência",
        "Data / Período": "13 de maio, 2026",
        "Local": "Houston, EUA",
        "Vertical / Tema principal": "Energia / Digital Twin / AI",
        "Soluções DSW com aderência": "Simcenter, Teamcenter, Insights Hub",
        "Público-alvo": "Indústria (Oil & Gas / Energy) / Líderes de Tech",
        "Organização responsável": "Future Conferences",
        "Site / URL": "https://futuredigitaltwin.com/events/fdt-usa-2026/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Evento ultra-especializado em gêmeo digital e IA para a vertical de energia.",
        "Oportunidade de atuação": "Patrocinador / Palestrante"
    },
    {
        "Nome do Evento": "InnovateEnergy Week 2026",
        "Tipo": "Summit / Feira",
        "Data / Período": "22-24 de junho, 2026",
        "Local": "Houston, EUA",
        "Vertical / Tema principal": "Energia / Robótica / Industrial AI",
        "Soluções DSW com aderência": "Simcenter, Insights Hub, Tecnomatix (Robotics)",
        "Público-alvo": "Indústria / Operadores de Ativos / Tech",
        "Organização responsável": "InnovateEnergy",
        "Site / URL": "https://innovateenergynow.com/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Convergência de robótica, IA e dados espaciais para operações industriais complexas.",
        "Oportunidade de atuação": "Patrocinador / Palestrante"
    },
    {
        "Nome do Evento": "productronica 2025",
        "Tipo": "Feira",
        "Data / Período": "18-21 de novembro, 2025",
        "Local": "Munique, Alemanha",
        "Vertical / Tema principal": "Eletrônicos & Semicondutores",
        "Soluções DSW com aderência": "Valor, Capital, Opcenter (Electronics)",
        "Público-alvo": "Indústria de Eletrônicos / Engenheiros",
        "Organização responsável": "Messe München",
        "Site / URL": "https://productronica.com/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Líder mundial em manufatura de eletrônicos; portfólio Valor/Capital é central aqui.",
        "Oportunidade de atuação": "Expositor"
    },
    {
        "Nome do Evento": "Semicon Europa 2026",
        "Tipo": "Feira",
        "Data / Período": "10-13 de novembro, 2026",
        "Local": "Munique, Alemanha",
        "Vertical / Tema principal": "Eletrônicos & Semicondutores",
        "Soluções DSW com aderência": "Capital (EDA), Teamcenter, Opcenter",
        "Público-alvo": "Indústria de Semicondutores",
        "Organização responsável": "SEMI",
        "Site / URL": "https://www.semiconeuropa.org/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Evento principal para a cadeia de suprimentos de semicondutores; aderência crítica a EDA.",
        "Oportunidade de atuação": "Expositor / Patrocinador"
    },
    {
        "Nome do Evento": "The smarter E South America 2026",
        "Tipo": "Feira / Summit",
        "Data / Período": "25-27 de agosto, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Energia & Utilities / e-Mobility / Solar",
        "Soluções DSW com aderência": "Simcenter, Solid Edge, Insights Hub, Mendix",
        "Público-alvo": "Indústria de Energia / Startups",
        "Organização responsável": "Solar Promotion / Messe München",
        "Site / URL": "https://www.intersolar.net.br/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Maior hub de energia solar e e-mobility da AL; vertical estratégica em rápida expansão no Brasil.",
        "Oportunidade de atuação": "Expositor / Palestrante"
    },
    {
        "Nome do Evento": "Expo Construção Offsite 2026",
        "Tipo": "Feira",
        "Data / Período": "16-19 de junho, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Construção Civil (AEC) / Construção Industrializada",
        "Soluções DSW com aderência": "NX (BIM/Industrialized), Teamcenter, Solid Edge",
        "Público-alvo": "Engenheiros / Arquitetos / Construtoras",
        "Organização responsável": "Expo Construção Offsite",
        "Site / URL": "https://www.expoconstrucaooffsite.com.br/",
        "Nível de relevância": "Média",
        "Justificativa Relevância": "Foco na transição da construção civil para a manufatura (industrialização da construção).",
        "Oportunidade de atuação": "Expositor / Participante"
    },
    {
        "Nome do Evento": "Mondial de l'Auto Paris 2026",
        "Tipo": "Feira / Expo",
        "Data / Período": "12-18 de outubro, 2026",
        "Local": "Paris, França",
        "Vertical / Tema principal": "Automotivo & e-Mobility",
        "Soluções DSW com aderência": "NX, Simcenter, Polarion, Teamcenter",
        "Público-alvo": "Indústria / Consumidores / Líderes Globais",
        "Organização responsável": "PFA / Hopscotch",
        "Site / URL": "https://mondial.paris/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Um dos maiores shows automotivos do mundo; vitrine para inovação em veículos elétricos e software-defined vehicles.",
        "Oportunidade de atuação": "Participante / Parceiro (via OEMs)"
    },
    {
        "Nome do Evento": "HIS - Healthcare Innovation Show 2026",
        "Tipo": "Summit / Feira",
        "Data / Período": "16-17 de setembro, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Ciências da Vida & MedTech / Inovação Digital",
        "Soluções DSW com aderência": "Mendix, Polarion, Teamcenter",
        "Público-alvo": "Líderes de Saúde / Startups / Tech",
        "Organização responsável": "Informa Markets",
        "Site / URL": "https://his.saudebusiness.com/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Foco em transformação digital e interoperabilidade na saúde; excelente para Mendix e Polarion.",
        "Oportunidade de atuação": "Patrocinador / Palestrante"
    },
    {
        "Nome do Evento": "SpaceBR Show 2026",
        "Tipo": "Feira / Summit",
        "Data / Período": "Maio, 2026 (a confirmar)",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Aeroespacial & Defesa",
        "Soluções DSW com aderência": "NX, Simcenter, Teamcenter",
        "Público-alvo": "Indústria Espacial / Governo / Startups",
        "Organização responsável": "MundoGEO",
        "Site / URL": "https://spacebrshow.com/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Único evento focado em 'New Space' na AL; vertical de alto crescimento e demanda por engenharia de precisão.",
        "Oportunidade de atuação": "Expositor / Palestrante"
    },
    {
        "Nome do Evento": "Automec 2026",
        "Tipo": "Feira",
        "Data / Período": "20-24 de abril, 2026 (a confirmar)",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Automotivo / Aftermarket / Manufatura",
        "Soluções DSW com aderência": "Solid Edge, NX, Teamcenter, Opcenter",
        "Público-alvo": "Indústria Automotiva / Autopeças",
        "Organização responsável": "RX Brasil",
        "Site / URL": "https://www.automecfeira.com.br/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Maior evento de autopeças e reparação da AL; crucial para a cadeia de fornecedores Tier 1 e Tier 2.",
        "Oportunidade de atuação": "Expositor / Patrocinador"
    },
    {
        "Nome do Evento": "Autocom 2026",
        "Tipo": "Feira",
        "Data / Período": "31 de março - 2 de abril, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Transportes / Automação Comercial",
        "Soluções DSW com aderência": "Mendix, Opcenter, Insights Hub",
        "Público-alvo": "Varejo / Logística / Tech",
        "Organização responsável": "AFRAC",
        "Site / URL": "https://www.feiraautocom.com.br/",
        "Nível de relevância": "Média",
        "Justificativa Relevância": "Foco em automação; tangencia o portfólio industrial na parte de logística e analytics.",
        "Oportunidade de atuação": "Expositor / Participante"
    },
    {
        "Nome do Evento": "Expobor 2026",
        "Tipo": "Feira",
        "Data / Período": "23-25 de junho, 2026",
        "Local": "São Paulo, Brasil",
        "Vertical / Tema principal": "Industrial Machinery / Borracha / Pneus",
        "Soluções DSW com aderência": "Simcenter, Opcenter, Teamcenter",
        "Público-alvo": "Indústria Química / Automotiva",
        "Organização responsável": "Francal",
        "Site / URL": "https://www.expobor.com.br/",
        "Nível de relevância": "Média",
        "Justificativa Relevância": "Vertical de nicho (borracha) com alta demanda por simulação física e execução de manufatura.",
        "Oportunidade de atuação": "Expositor"
    },
    {
        "Nome do Evento": "Mendix Connect Portugal",
        "Tipo": "Workshop / Summit",
        "Data / Período": "1 de julho, 2026",
        "Local": "Amadora, Portugal",
        "Vertical / Tema principal": "Low-code / Industrial Apps",
        "Soluções DSW com aderência": "Mendix, Agentic AI",
        "Público-alvo": "Líderes de TI / Indústria",
        "Organização responsável": "Mendix / Siemens Portugal",
        "Site / URL": "https://www.mendix.com/events/",
        "Nível de relevância": "Média",
        "Justificativa Relevância": "Focado em low-code e IA para acelerar a transformação digital em clientes existentes.",
        "Oportunidade de atuação": "Organizador / Palestrante"
    },
    {
        "Nome do Evento": "Mendix Customer Connect DACH",
        "Tipo": "Workshop / Summit",
        "Data / Período": "26 de março, 2026",
        "Local": "Frankfurt, Alemanha",
        "Vertical / Tema principal": "Low-code / Automotivo",
        "Soluções DSW com aderência": "Mendix, RapidMiner",
        "Público-alvo": "Indústria (Automotive focus) / Usuários",
        "Organização responsável": "Mendix",
        "Site / URL": "https://www.mendix.com/events/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Focado em casos de sucesso no setor automotivo alemão; altamente estratégico para benchmarking.",
        "Oportunidade de atuação": "Organizador / Palestrante"
    },
    {
        "Nome do Evento": "Campus Party Brasil 2026 (CPBR18)",
        "Tipo": "Bootcamp / Hackathon",
        "Data / Período": "3-7 de junho, 2026",
        "Local": "Brasília, Brasil",
        "Vertical / Tema principal": "STEM / Tecnologia / Espacial",
        "Soluções DSW com aderência": "Mendix, Solid Edge (Academia)",
        "Público-alvo": "Estudantes / Startups / Makers",
        "Organização responsável": "Instituto Campus Party",
        "Site / URL": "https://brasil.campus-party.org/",
        "Nível de relevância": "Baixa",
        "Justificativa Relevância": "Focado em talentos e marca; bom para hackathons Mendix e visibilidade acadêmica.",
        "Oportunidade de atuação": "Patrocinador / Palestrante"
    },
    {
        "Nome do Evento": "Minas Summit 2026",
        "Tipo": "Summit / Demo Day",
        "Data / Período": "17-18 de junho, 2026",
        "Local": "Belo Horizonte, Brasil",
        "Vertical / Tema principal": "Ecossistema de Inovação Regional",
        "Soluções DSW com aderência": "Mendix, Siemens Xcelerator para Startups",
        "Público-alvo": "Startups / Indústria (Mineração/Energia) / Investidores",
        "Organização responsável": "FCJ Group",
        "Site / URL": "https://minassummit.com/",
        "Nível de relevância": "Média",
        "Justificativa Relevância": "Principal hub de inovação em MG; aderência com as verticais de mineração e manufatura regional.",
        "Oportunidade de atuação": "Patrocinador / Palestrante"
    },
    {
        "Nome do Evento": "Rio2C 2026",
        "Tipo": "Conferência / Summit",
        "Data / Período": "26-31 de maio, 2026",
        "Local": "Rio de Janeiro, Brasil",
        "Vertical / Tema principal": "Criatividade / Inovação / Tech",
        "Soluções DSW com aderência": "Mendix, Gêmeo Digital (Cidades/Entretenimento)",
        "Público-alvo": "Misto / Criativos / Tech",
        "Organização responsável": "Rio2C",
        "Site / URL": "https://www.rio2c.com/",
        "Nível de relevância": "Baixa",
        "Justificativa Relevância": "Evento mais voltado para criatividade, mas com trilhas de inovação que podem tangenciar Smart Cities.",
        "Oportunidade de atuação": "Participante / Palestrante"
    },
    {
        "Nome do Evento": "Viva Technology 2026",
        "Tipo": "Expo / Summit",
        "Data / Período": "17-20 de junho, 2026",
        "Local": "Paris, França",
        "Vertical / Tema principal": "Startups / Inovação Global / AI",
        "Soluções DSW com aderência": "Mendix, Industrial AI, Sustainability solutions",
        "Público-alvo": "Startups / VCs / Big Tech",
        "Organização responsável": "Publicis / Les Echos",
        "Site / URL": "https://vivatechnology.com/",
        "Nível de relevância": "Média",
        "Justificativa Relevância": "Evento massivo de startups na Europa; Siemens costuma ter presença via parcerias.",
        "Oportunidade de atuação": "Patrocinador / Parceiro"
    },
    {
        "Nome do Evento": "Mendix: Capture The Flag",
        "Tipo": "Hackathon",
        "Data / Período": "Outubro, 2025 (benchmarking para 2026)",
        "Local": "Hybrid (Global)",
        "Vertical / Tema principal": "Low-code / Software Development",
        "Soluções DSW com aderência": "Mendix, Agentic AI",
        "Público-alvo": "Desenvolvedores / Makers",
        "Organização responsável": "Mendix",
        "Site / URL": "https://community.xcelerator.siemens.com/",
        "Nível de relevância": "Alta",
        "Justificativa Relevância": "Principal hackathon global da Mendix; fomenta a comunidade de desenvolvedores.",
        "Oportunidade de atuação": "Organizador"
    }
]

if __name__ == "__main__":
    if os.path.exists('events_data.json'):
        os.remove('events_data.json')

    collector = EventCollector()
    for event in events_to_add:
        collector.add_event(event)
    print(f"Total events collected: {collector.get_count()}")
